### ISSUE TITLE
Can I use this in ROS1(Ubuntu 1804)?

### ISSUE THREAD

**Issue by Dlemand** [ctu-vras/steam-deck-ros-controller#2]
Hello , this is a good project! I am using Ubuntu1804 ROS Melodic by distrobox.  \
Can i just use the src folder to build the project? or it need some drivers?

**Comment by peci1** [comment]
Hi, I don't understand what you are asking. There is no "project" here in this repo. It is just a set of configuration files. And it is not meant to work with distrobox - it is meant to work with conda, which are two very distinct approaches.

**Comment by Dlemand** [comment]
> Hi, I don't understand what you are asking. There is no "project" here in this repo. It is just a set of configuration files. And it is not meant to work with distrobox - it is meant to work with conda, which are two very distinct approaches.

i mean if i can use the ```workspaces/deck_ws/src``` filses to ```catkin build```in an Independent Ubuntu ROS environment？not the steamOS.

or I just need to build the jsk repo to use steamdeck controller in ros?

**Comment by peci1** [comment]
I'm still not quite getting what you want to achieve. The three .repos files in `deck_ws/src` are just examples of what you can have on the Deck (in particular, it is the workspace content we have on our Deck to visualize data from our robots). You could definitely reuse the `audio.repos` to install `sound_play` package so that the Deck can talk to you via a topic, and you could probably reuse `jsk.repos` which add a bunch of very useful RViz plugins. `cras.repos` is probably of low value to you as it contains mostly our lab-specific things, some of them not publicly available. In the other two repos, just make sure to replace all `noetic-devel` with `melodic-devel` if you're on Melodic.

However, these 3 repos files do not contain any core part of ROS. That is already expected to be installed. If you're looking for a way to install Melodic from source, then follow this wiki: http://wiki.ros.org/melodic/Installation/Source .

**Comment by Dlemand** [comment]
Thanks a lot. I may misunderstood your title:**steam-deck-ros-controller**． \
i mistakenly thought it aims to run the steamdeck as a gamecontroller like Xbox to publish cmd_vel msgs ;

**Comment by peci1** [comment]
Yes, that's possible, but you don't need any workspace for that. See this paragraph from README:

> Tap the Steam icon in taskbar, select Settings -> Controller -> Desktop configuration. This menu allows you to configure the gamepad behavior, so that the joy_node can read it. Press X to browse available configs. Select Templates->Gamepad->Apply configuration. Do any other adjustments you like, but do not touch the JOYSTICK MOVE areas. You can't return these values back! What I do is configure L4 as Ctrl+R, L5 as Ctrl+C, R4 as up arrow and R5 as down arrow.

So you just run a normal `joy_node` and the axes and buttons are published to ROS.
